Repository supurazako/makiMakiStream, pull requests merged in 2025-04, with the labels that each got.

#12 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#11 Refactor/managing state
  app/atoms.ts
  app/components/video_controllers.tsx
  app/interfaces.tsx
  app/routes/dev.video_controllers.tsx
  package-lock.json
  package.json
Labels: enhancement, refactor

#15 [Refactor] 状態管理の改善 シーズン2（async編）
  @types/twitch-embed.d.ts
  app/atoms.ts
  app/components/common/modal.tsx
  app/components/twitchStreamContainer.tsx
  app/components/video_controllers.tsx
  app/interfaces.tsx
  app/models/playerModel.ts
  app/models/twitchPlayerModel.ts
  app/models/videoDataModel.ts
  app/routes/dev.video_controllers.tsx
Labels: enhancement

#18 動画を追加するModalの再実装
  app/atoms.ts
  app/components/common/modal.tsx
  app/components/modal/AddVideoModal.tsx
  app/components/video_controllers.tsx
  app/routes/dev.video_controllers.tsx
  app/styles/common/modal.css
Labels: bug, enhancement

#23 グローバルコントローラーの実装
  app/atoms.ts
  app/components/ControlItemSkeleton.tsx
  app/components/GlobalController.tsx
  app/components/GlobalMuteControl.tsx
  app/components/GlobalPlayControl.tsx
  app/components/common/icons.tsx
  app/routes/dev.global-controller.tsx
  app/styles/control-item-skeleton.css
  app/styles/global-controller.css
Labels: enhancement
