Repository supurazako/makiMakiStream, pull requests merged in 2025-05, with the labels that each got.

#25 Refactor/video controller
  app/components/modal/AddVideoModal.tsx
  app/components/video-controller/AddVideoButton.tsx
  app/components/video-controller/PlayControl.tsx
  app/components/video-controller/RemoveControl.tsx
  app/components/video-controller/VideoController.tsx
  app/components/video-controller/VideoControllersContainer.tsx
  app/components/video-controller/VolumeControl.tsx
  app/models/videoDataModel.ts
  app/routes/dev.video-controllers-refactor.tsx
  app/styles/add-video-button.css
  app/styles/video-controller.css
  app/styles/video-controllers-container.css
Labels: enhancement, refactor

#35 Feat/layout option when video count is 0 or above 5
  app/components/StartScreen.tsx
  app/components/layout-selector/LayoutSelector.tsx
  app/routes/_index.tsx
  app/styles/layout-selector.css
  app/styles/start-screen.css
  app/styles/videos-container.css
  public/icons/layout-option-1A.svg
  public/icons/layout-option-above-5.svg
Labels: bug, enhancement, essential

#40 Feat/react router v7/39
  .gitignore
  app/components/modal/AddVideoModal.tsx
  app/entry.client.tsx
  app/entry.server.tsx
  app/root.tsx
  app/routes.ts
  app/routes/_index.tsx
  app/routes/dev.sidebar.tsx
  app/routes/dev.video_controllers.tsx
  app/tailwind.css
  package-lock.json
  package.json
  postcss.config.js
  react-router.config.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#38 [fix] YouTube Embedが正しくマウント・アンマウントされるように
  app/.client/utils/loadYouTubeAPI.ts
  app/components/embed/YouTubeVideoEmbed.tsx
Labels: bug
