Repository supurazako/makiMakiStream, pull requests merged in 2025-06, with the labels that each got.

#49 deploy cloudflare
  .gitignore
  app.ts
  app/.server/utils/twitch.ts
  app/components/modal/AddVideoModal.tsx
  app/entry.server.tsx
  app/routes/_index.tsx
  package-lock.json
  package.json
  tsconfig.json
  vite.config.ts
  worker-configuration.d.ts
  wrangler.toml
Labels: enhancement

#47 [fix] ボリュームアイコンが段階的に変化するように
  app/components/GlobalMuteControl.tsx
  app/components/common/icons.tsx
  app/components/video-controller/VolumeControl.tsx
  app/components/video_controllers.tsx
Labels: bug

#42 [fix] 動画追加モーダルの検索に500msのデバウンスを実装
  app/components/modal/AddVideoModal.tsx
  app/hooks/useDebouncedEffect.ts
Labels: bug

#51 fix: LOW_VOLUME_THRESHOLD を定義
  app/components/video-controller/VolumeControl.tsx
Labels: bug

#52 Refactor/super super refactor
  app/.server/utils/twitch.ts
  app/atoms.ts
  app/common/common.css
  app/components/Sidebar.tsx
  app/components/StartScreen.tsx
  app/components/TwitchEmbed.tsx
  app/components/VideosContainer.tsx
  app/components/YoutubeBox.tsx
  app/components/common/Modal.tsx
  app/components/common/modal.css
  app/components/controller/ControlItemSkeleton.tsx
  app/components/controller/PlayControl.tsx
  app/components/controller/RemoveControl.tsx
  app/components/controller/VolumeControl.tsx
  app/components/controller/global-controller/GlobalController.tsx
  app/components/controller/global-controller/GlobalMuteControl.tsx
  app/components/controller/global-controller/GlobalPlayControl.tsx
  app/components/controller/video-controller/AddVideoButton.tsx
  app/components/controller/video-controller/ChannelNameLabel.tsx
  app/components/controller/video-controller/VideoController.tsx
  app/components/controller/video-controller/VideoControllersContainer.tsx
  app/components/controller/video-controller/VideoTitleLabel.tsx
  app/components/embed/TwitchVideoEmbed.tsx
  app/components/layout_options.css
  app/components/layout_options.tsx
  app/components/modal/AddVideoModal.tsx
  app/components/sidebar.css
  app/components/sidebar.tsx
  app/components/twitch-stream-box.tsx
  app/components/url-form.tsx
  app/components/video_controllers.css
  app/components/video_controllers.tsx
  app/entry.client.tsx
  app/entry.server.tsx
  app/root.tsx
  app/routes/_index.tsx
  app/routes/dev.global-controller.tsx
  app/routes/dev.layout-selector.tsx
  app/routes/dev.layout_options.tsx
  app/routes/dev.sidebar.tsx
  app/routes/dev.video-controllers-refactor.tsx
  app/routes/dev.video_controllers.tsx
  app/routes/dev.youtubeBox.tsx
  app/routes/url-form-demo.tsx
  app/styles/global-controller.css
  app/styles/layout-selector.css
  app/styles/sidebar.css
  app/styles/start-screen.css
  app/utils/RegularExpression.tsx
  vite.config.ts.timestamp-1746603440590-b17c91ebeb6d7.mjs
  vite.config.ts.timestamp-1746610784516-d53f9a31183a4.mjs
  vite.config.ts.timestamp-1746702115646-2cca12c410e73.mjs
Labels: refactor
